
<%def name="build(file)">[url=${file.url}]${file.filename}[/url]</%def>

Please note: I'll clean this up in the next 24 hours. These changes need to be grouped (i.e. scripting, FRED, ...) to make this list less overwhelming. --ngld

[b]Change log:[/b] (chronologically ordered)
[list]
[li]Merge pull request #3878 from Goober5000/timer_preliminary_cleanup [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3878](details)[/url][/li]
[li]Merge pull request #3688 from z64555/fix/issue_3685 [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3688](details)[/url][/li]
[li]Safety for replace-texture (#3694) [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3694](details)[/url][/li]
[li]Actually fix the goal's target being sent (#3665) [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3665](details)[/url][/li]
[li]Merge pull request #3695 from Baezon/fix-visibility-initialization [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3695](details)[/url][/li]
[li]Merge pull request #3696 from Baezon/fix-secondary-has-ammo [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3696](details)[/url][/li]
[li]Fix warnings concerning ballistic weapons (#3683) [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3683](details)[/url][/li]
[li]Merge pull request #3671 from Goober5000/moar_sexp_documentation [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3671](details)[/url][/li]
[li]Animation Overhaul: Phase 2 (#3609) [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3609](details)[/url][/li]
[li]add no evasion flag (#3677) [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3677](details)[/url][/li]
[li]Wrap Docking getTime in a timestamp (#3701) [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3701](details)[/url][/li]
[li]Merge pull request #3608 from Goober5000/perform_actions_etc [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3608](details)[/url][/li]
[li]Simplistic Ship Transparency (#3436) [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3436](details)[/url][/li]
[li]Add New Options to Wingmen Gauge (#3703) [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3703](details)[/url][/li]
[li]Add getColor to lua gr library, which returns the active color (#3687) [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3687](details)[/url][/li]
[li]Add Per-Ship Class Wingmen Status Dot (#3711) [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3711](details)[/url][/li]
[li]Merge pull request #3702 from Baezon/use-real-names-cheats [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3702](details)[/url][/li]
[li]Custom data in tables, tackling #3699 (#3707) [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3699](details)[/url][/li]
[li]Add velocity inheritance for particle effects (#3691) [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3691](details)[/url][/li]
[li]Merge pull request #3713 from Goober5000/submodel_rotate_reorg [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3713](details)[/url][/li]
[li]Fix load order problems caused by Iff vectorization  (#3718) [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3718](details)[/url][/li]
[li]Merge pull request #3719 from Goober5000/adjust_rotator_flag [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3719](details)[/url][/li]
[li]karajorma's SEXP containers, Part 2: Persistence (#3462) [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3462](details)[/url][/li]
[li]Scale distant combat related effects so they stay visible (#3656) [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3656](details)[/url][/li]
[li]Merge pull request #3722 from EatThePath/ShaderCleanup [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3722](details)[/url][/li]
[li]Merge pull request #3726 from Goober5000/pre_translation_cleanup [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3726](details)[/url][/li]
[li]Merge pull request #3728 from Goober5000/sexp_replace_texture_edits [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3728](details)[/url][/li]
[li]Add +arrival rvec for ship bays (#3698) [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3698](details)[/url][/li]
[li]Merge pull request #3731 from Goober5000/state_end_script_hooks [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3731](details)[/url][/li]
[li]Merge pull request #3735 from BMagnu/secondary_no_ammo_turret_fix [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3735](details)[/url][/li]
[li]Merge pull request #3732 from EatThePath/safety-animation [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3732](details)[/url][/li]
[li]Add 'passive' lightning arcs to ships (#3733) [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3733](details)[/url][/li]
[li]Bump PLR/CSG versions and preserve pre-containers compatibility (#3739) [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3739](details)[/url][/li]
[li]Merge pull request #3724 from Goober5000/hud_gauge_expanded_check [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3724](details)[/url][/li]
[li]Merge pull request #3736 from EatThePath/gr_set_lighting-cleanup [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3736](details)[/url][/li]
[li]Add Bomb-locking secondaries (#3588) [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3588](details)[/url][/li]
[li]Add nullptr safety for animations (#3738) [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3738](details)[/url][/li]
[li]Remove 'stream' weapon handling (#3720) [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3720](details)[/url][/li]
[li]Merge pull request #3697 from Baezon/animated-neb-poofs [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3697](details)[/url][/li]
[li]Merge pull request #3746 from Goober5000/scripting_neb2_awacs [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3746](details)[/url][/li]
[li]Merge pull request #3754 from notimaginative/fix_escort_list_stealth_cull [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3754](details)[/url][/li]
[li]Merge pull request #3750 from Goober5000/better_argument_syntax_checking [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3750](details)[/url][/li]
[li]Merge pull request #3755 from Goober5000/script_eval_bool [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3755](details)[/url][/li]
[li]Merge pull request #3741 from Shivansps/missing_updatedata [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3741](details)[/url][/li]
[li]Fix Crash On second opening of select box cause by #3634 (#3760) [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3634](details)[/url][/li]
[li]Merge pull request #3743 from Goober5000/gamesnd_tweaks [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3743](details)[/url][/li]
[li]Merge pull request #3749 from ngld/refactor/ci [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3749](details)[/url][/li]
[li]Add head-on laser bitmaps (#3748) [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3748](details)[/url][/li]
[li]Merge pull request #3764 from Goober5000/fix_rand32f [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3764](details)[/url][/li]
[li]Merge pull request #3745 from Goober5000/target_spelling [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3745](details)[/url][/li]
[li]Split From #3674 Flags Dialog (#3714) [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3674](details)[/url][/li]
[li]Split From #3674 Ship Editor Bugfixes (#3716) [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3674](details)[/url][/li]
[li]Merge pull request #3761 from Goober5000/fix_3758 [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3761](details)[/url][/li]
[li]Merge pull request #3767 from Goober5000/sexp_variable_protecc [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3767](details)[/url][/li]
[li]add destroy-instantly-with-debris (#3752) [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3752](details)[/url][/li]
[li]Merge pull request #3717 from TaGenius/feature/QtGoalsDialog [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3717](details)[/url][/li]
[li]Merge pull request #3715 from TaGenius/feature/QtInitialStatusEditor [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3715](details)[/url][/li]
[li]Expose nebula visibility factors (#3676) [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3676](details)[/url][/li]
[li]Ai use lock status for optimum range choice (#3762) [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3762](details)[/url][/li]
[li]Merge pull request #3765 from Goober5000/subtitle_line_height [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3765](details)[/url][/li]
[li]Merge pull request #3779 from scp-fs2open/fix/nightly-trigger-pat [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3779](details)[/url][/li]
[li]add flag for toggling ship passive lightning (#3772) [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3772](details)[/url][/li]
[li]Merge pull request #3780 from scp-fs2open/fix/nightly-build-cond [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3780](details)[/url][/li]
[li]Merge pull request #3783 from scp-fs2open/revert-3780-fix/nightly-build-cond [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3783](details)[/url][/li]
[li]Merge pull request #3784 from scp-fs2open/revert-3779-fix/nightly-trigger-pat [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3784](details)[/url][/li]
[li]Merge pull request #3785 from scp-fs2open/revert-3749-refactor/ci [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3785](details)[/url][/li]
[li]Merge pull request #3786 from Goober5000/submodel_turn_accel [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3786](details)[/url][/li]
[li]Merge pull request #3774 from Goober5000/multiple_event_check [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3774](details)[/url][/li]
[li]dont exclude primary targets from dead targeting (#3781) [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3781](details)[/url][/li]
[li]take into account glow size for glow head on (#3787) [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3787](details)[/url][/li]
[li]dont do passive lightning on destroyed subsystems (#3771) [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3771](details)[/url][/li]
[li]Merge pull request #3790 from Kiloku/rotated-rect-use-radians [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3790](details)[/url][/li]
[li]Merge pull request #3777 from Kiloku/draw_rotated_images [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3777](details)[/url][/li]
[li]Merge pull request #3791 from EatThePath/animation_safety2 [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3791](details)[/url][/li]
[li]Merge pull request #3734 from notimaginative/cfilesystem_cleanup [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3734](details)[/url][/li]
[li]correctly position tail for laser head on glows (#3789) [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3789](details)[/url][/li]
[li]load techroom model subsystems into seperate buffer (#3796) [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3796](details)[/url][/li]
[li]Lt22 (#3801) [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3801](details)[/url][/li]
[li]Expose turret re-targeting delay (#3803) [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3803](details)[/url][/li]
[li]consistent capitalization (#3805) [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3805](details)[/url][/li]
[li]Fix the tonemapper strings (#3806) [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3806](details)[/url][/li]
[li]Fix Default Sound Levels in Game Settings Table (#3809) [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3809](details)[/url][/li]
[li]Merge pull request #3810 from EatThePath/lab-doc-fix [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3810](details)[/url][/li]
[li]Merge pull request #3800 from Kiloku/draw_objects_by_center [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3800](details)[/url][/li]
[li]Merge pull request #3704 from Baezon/asteroid-arbitrary-targets [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3704](details)[/url][/li]
[li]Merge pull request #3798 from TheForce172/feature/SubstituteShipLabel [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3798](details)[/url][/li]
[li]Merge pull request #3797 from TheForce172/feature/QTShipEditorSubdialogs2 [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3797](details)[/url][/li]
[li]Merge pull request #3799 from TheForce172/feature/PlayerOrdersDialog [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3799](details)[/url][/li]
[li]Animation Rework: Phase 3 (#3793) [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3793](details)[/url][/li]
[li]Expose OSWPT to Lua and allow for LuaSEXP argument (#3637) [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3637](details)[/url][/li]
[li]Merge pull request #3813 from notimaginative/fix_get-file-list_length_bug [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3813](details)[/url][/li]
[li]Merge pull request #3814 from notimaginative/fix_hud_config_loading [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3814](details)[/url][/li]
[li]Set Default Detail Levels to be Consistent at Ultra Settings (#3811) [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3811](details)[/url][/li]
[li]Merge pull request #3816 from Goober5000/fred_ui_updates [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3816](details)[/url][/li]
[li]Merge pull request #3820 from notimaginative/reduce_bsp_align_memory [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3820](details)[/url][/li]
[li]Merge pull request #3838 from EatThePath/fix-bad-const-uniforms [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3838](details)[/url][/li]
[li]Merge pull request #3843 from Goober5000/polymodel_instance_update [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3843](details)[/url][/li]
[li]Merge pull request #3844 from notimaginative/fix_awacs_multi_crash [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3844](details)[/url][/li]
[li]Clarify logging when loading thruster textures as static images (#3839) [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3839](details)[/url][/li]
[li]Merge pull request #3837 from Goober5000/sexp_error_location [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3837](details)[/url][/li]
[li]Merge pull request #3845 from Goober5000/fix_assert [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3845](details)[/url][/li]
[li]improve PXO data validation code (#3817) [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3817](details)[/url][/li]
[li]Animation Rework Phase 3 - Fixes for Multi (#3846) [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3846](details)[/url][/li]
[li]Fix random selection of points for SphereShape particles (#3841) [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3841](details)[/url][/li]
[li]improve handling of PXO lobby banners: (#3819) [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3819](details)[/url][/li]
[li]Merge pull request #3851 from Goober5000/custom_language_fix [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3851](details)[/url][/li]
[li]karajorma's SEXP containers, Part 5: Sexp_nodes (#3495) [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3495](details)[/url][/li]
[li]Make secondaries use $energy consumed (#3847) [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3847](details)[/url][/li]
[li]Fix weapons with submodel rotation firing (#3850) [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3850](details)[/url][/li]
[li]Merge pull request #3856 from Baezon/phys-info-ab-speed-display [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3856](details)[/url][/li]
[li]Merge pull request #3858 from notimaginative/fix_ship_subsys_mem_leak [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3858](details)[/url][/li]
[li]Merge pull request #3864 from jg18/events-editor-esc-check [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3864](details)[/url][/li]
[li]Merge pull request #3868 from notimaginative/fix_awacs_team_mem [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3868](details)[/url][/li]
[li]Merge pull request #3867 from notimaginative/fix_object_collider_mem [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3867](details)[/url][/li]
[li]Merge pull request #3866 from notimaginative/fix_warnings_errors [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3866](details)[/url][/li]
[li]take pathtype extensions into account during file indexing (#3869) [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3869](details)[/url][/li]
[li]Merge pull request #3871 from Goober5000/fix_fred_crash [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3871](details)[/url][/li]
[li]Merge pull request #3873 from Goober5000/nonfatal_sexp_errors [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3873](details)[/url][/li]
[li]clarity function for homing objects and fix scripting target setting (#3865) [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3865](details)[/url][/li]
[li]Moved the PPC tonemapper intermediate calculations to C-side to clean up shader compatibility with older versions of opengl (#3857) [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3857](details)[/url][/li]
[li]Merge pull request #3878 from Goober5000/timer_preliminary_cleanup [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3878](details)[/url][/li]
[li]Merge pull request #3881 from EatThePath/ppc-safety [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3881](details)[/url][/li]
[li]Animation Rework Phase 3, Turret fix (#3877) [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3877](details)[/url][/li]
[li]Fix Particles pageIn to use nframes (#3884) [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3884](details)[/url][/li]
[li]Merge pull request #3886 from Goober5000/small_skybox_cleanup [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3886](details)[/url][/li]
[li]Merge pull request #3887 from notimaginative/file_load_fixes [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3887](details)[/url][/li]
[li]Merge pull request #3888 from Goober5000/fs1_target_behavior [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3888](details)[/url][/li]
[li]Controls 4 and 5 - Multi-joy and Preset Files (#2958) [url=https://github.com/scp-fs2open/fs2open.github.com/pull/2958](details)[/url][/li]
[li]Fix Particle PageIn (V2) (#3893) [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3893](details)[/url][/li]
[li]Handle forgotten 0 case for new vecmat function (#3891) [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3891](details)[/url][/li]
[li]Revert timestamp changes for HUD (#3895) [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3895](details)[/url][/li]
[li]Merge pull request #3898 from z64555/fix/issue_3892 [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3898](details)[/url][/li]
[li]Merge pull request #3897 from Goober5000/fix_first_of [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3897](details)[/url][/li]
[li]Merge pull request #3900 from z64555/fix/issue_3892a [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3900](details)[/url][/li]
[li]Merge pull request #3872 from notimaginative/dynamic_cfile_blocks [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3872](details)[/url][/li]
[li]Merge pull request #3909 from Goober5000/fix_3907 [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3909](details)[/url][/li]
[li]Merge pull request #3908 from wookieejedi/ttf-support-for-multi-screens [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3908](details)[/url][/li]
[li]Merge pull request #3885 from qazwsxal/lightshaft_fix [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3885](details)[/url][/li]
[li]Merge pull request #3880 from EatThePath/lt_lab [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3880](details)[/url][/li]
[li]Properly handle negative case (#3910) [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3910](details)[/url][/li]
[li]Merge pull request #3905 from z64555/fix/issue_3901 [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3905](details)[/url][/li]
[li]Animation Rework, Phase 4: Moveables (#3904) [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3904](details)[/url][/li]
[li]Add AI to Fix Negative Turret Ammo (#3913) [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3913](details)[/url][/li]
[li]Fix issue #3912 (#3914) [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3912](details)[/url][/li]
[li]Implements Save (#3922) [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3922](details)[/url][/li]
[li]Fix incorrect net signature for wave ships (#3924) [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3924](details)[/url][/li]
[li]Allow AI flag for bay orientation to account for parent `uvec` (#3925) [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3925](details)[/url][/li]
[li]FFmpeg deprecations fix for FFmpeg >= 5 (#3927) [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3927](details)[/url][/li]
[li]properly calc anim for instant (#3928) [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3928](details)[/url][/li]
[li]Fix first person glows (#3882) [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3882](details)[/url][/li]
[li]Merge pull request #3931 from wookieejedi/revert-mission-music-change [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3931](details)[/url][/li]
[li]Fix Bay Door Animations for Multi and Lone Player Ship (#3932) [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3932](details)[/url][/li]
[li]fix missing texture bug on standalone (#3937) [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3937](details)[/url][/li]
[li]Merge pull request #3879 from Goober5000/timestamp_redesign [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3879](details)[/url][/li]
[li]Merge pull request #3938 from Goober5000/notify_about_scroll_buttons [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3938](details)[/url][/li]
[li]Remove unnecessary/leaky strdup() calls in sexp_list_item in FRED/QtFRED (#3940) [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3940](details)[/url][/li]
[li]Merge pull request #3923 from notimaginative/standalone_optimizations [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3923](details)[/url][/li]
[li]update ffmpeg support for 5.0+ API changes (#3939) [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3939](details)[/url][/li]
[li]Merge pull request #3943 from Goober5000/tbp_warp_fix [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3943](details)[/url][/li]
[li]Remove unneeded/leaky code from sexp_list_item in FRED and QtFRED (#3942) [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3942](details)[/url][/li]
[li]Merge pull request #3944 from notimaginative/fix_training_mission_stats_bug [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3944](details)[/url][/li]
[li]Merge pull request #3945 from Goober5000/timestamp_debugging_hack [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3945](details)[/url][/li]
[li]Clean up Player_orders (#3918) [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3918](details)[/url][/li]
[li]Update links and edit text in FRED's and qtFRED's About dialogs (#3941) [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3941](details)[/url][/li]
[li]Merge pull request #3936 from Goober5000/dockpoint_moving_submodel [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3936](details)[/url][/li]
[li]Merge pull request #3948 from Goober5000/fix_3946 [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3948](details)[/url][/li]
[li]Merge pull request #3953 from Goober5000/small_fixes [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3953](details)[/url][/li]
[li]Merge pull request #3949 from notimaginative/psnet_ip_mode_pref [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3949](details)[/url][/li]
[li]Merge pull request #3950 from Goober5000/more_timestamp_fixes [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3950](details)[/url][/li]
[li]Fix/issue 3902 (#3947) [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3947](details)[/url][/li]
[li]Fix reverse instant trigger edge case (#3956) [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3956](details)[/url][/li]
[li]Fix lab animation triggers (#3965) [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3965](details)[/url][/li]
[li]Inverse Kinematics for Animations (#3962) [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3962](details)[/url][/li]
[li]Enable `Use Cargo Icon` for briefing icons (#3964) [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3964](details)[/url][/li]
[li]Add axis rotation Animation Segment (#3966) [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3966](details)[/url][/li]
[li]Add `getHUDConfigShowStatus` for scripting (#3961) [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3961](details)[/url][/li]
[li]Fix missing sound stop for non-flipped sound segments (#3969) [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3969](details)[/url][/li]
[li]Merge pull request #3970 from Goober5000/submodel_rotation_lod_fix [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3970](details)[/url][/li]
[li]Merge pull request #3974 from Goober5000/fred_bbox_fix [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3974](details)[/url][/li]
[li]Merge pull request #3972 from BMagnu/anim_4_fixes [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3972](details)[/url][/li]
[li]fix initial positions of submodels in FRED (#3975) [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3975](details)[/url][/li]
[li]Merge pull request #3978 from Goober5000/axis_inversion_upgrade [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3978](details)[/url][/li]
[li]Improve Animation SEXP usability (#3976) [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3976](details)[/url][/li]
[li]Fix edge case for turret lookup with template and display name (#3981) [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3981](details)[/url][/li]
[li]Merge pull request #3979 from Goober5000/model_translation_phase_1 [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3979](details)[/url][/li]
[li]Fix Damage Gauge Display (#3987) [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3987](details)[/url][/li]
[li]Merge pull request #3990 from Goober5000/fix_broken_rotation [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3990](details)[/url][/li]
[li]Merge pull request #3991 from JohnAFernandez/fix-edge-case-rollback-crash [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3991](details)[/url][/li]
[li]Merge pull request #3989 from Goober5000/fix_3889 [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3989](details)[/url][/li]
[li]Merge pull request #3993 from JohnAFernandez/Fix-client-zombie-missiles [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3993](details)[/url][/li]
[li]Fix limitations of GetColor script function (#3992) [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3992](details)[/url][/li]
[li]fix absolute moveable (#3995) [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3995](details)[/url][/li]
[li]Merge pull request #4002 from Goober5000/set_skybox_check [url=https://github.com/scp-fs2open/fs2open.github.com/pull/4002](details)[/url][/li]
[li]Merge pull request #4001 from The-E/fix/4000_mainhall_misc_anim_delay [url=https://github.com/scp-fs2open/fs2open.github.com/pull/4001](details)[/url][/li]
[li]Merge pull request #4003 from Goober5000/hud_gauge_and_string_upgrades [url=https://github.com/scp-fs2open/fs2open.github.com/pull/4003](details)[/url][/li]
[li]Merge pull request #4006 from Goober5000/fixed_missile_detonation [url=https://github.com/scp-fs2open/fs2open.github.com/pull/4006](details)[/url][/li]
[li]Merge pull request #4007 from Goober5000/fix_camera_orient [url=https://github.com/scp-fs2open/fs2open.github.com/pull/4007](details)[/url][/li]
[li]Fix rotation localization (#4012) [url=https://github.com/scp-fs2open/fs2open.github.com/pull/4012](details)[/url][/li]
[li]Merge pull request #4015 from Goober5000/operator_patches [url=https://github.com/scp-fs2open/fs2open.github.com/pull/4015](details)[/url][/li]
[li]Merge pull request #4014 from Goober5000/event_log_tweaks [url=https://github.com/scp-fs2open/fs2open.github.com/pull/4014](details)[/url][/li]
[li]Merge pull request #4019 from BMagnu/anim_axisrot_fix2 [url=https://github.com/scp-fs2open/fs2open.github.com/pull/4019](details)[/url][/li]
[li]Restrict allowable characters for preset names (#4009) [url=https://github.com/scp-fs2open/fs2open.github.com/pull/4009](details)[/url][/li]
[li]Merge pull request #4022 from Goober5000/ui_timestamp [url=https://github.com/scp-fs2open/fs2open.github.com/pull/4022](details)[/url][/li]
[li]Improve Pilot version checks (#3988) [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3988](details)[/url][/li]
[li]Treat Mouse as Joy0 if "turned on" in options menu (#3954) [url=https://github.com/scp-fs2open/fs2open.github.com/pull/3954](details)[/url][/li]
[li]Merge pull request #4024 from scp-fs2open/revert-3954-mouse_to_joy0 [url=https://github.com/scp-fs2open/fs2open.github.com/pull/4024](details)[/url][/li]
[li]Merge pull request #4025 from z64555/mouse_to_joy0 [url=https://github.com/scp-fs2open/fs2open.github.com/pull/4025](details)[/url][/li]
[/list]

[b]Deprecations:[/b]
[list]
[li][url=https://github.com/scp-fs2open/fs2open.github.com/pull/3472][font=Courier]script-eval[/font] has been deprecated in favor of script-eval-block[/url][/li]
[li][url=https://github.com/scp-fs2open/fs2open.github.com/pull/3370]renamed [font=Courier]hud-set-retail-gauge-active[/font] to [font=Courier]hud-set-builtin-gauge-active[/font][/url][/li]
[/list]

Deprecations are a mechanism in FSO where a certain feature or aspect of the engine has changed or is no longer supported. Since this would normally break existing mods we have the mod table feature "[tt]$Target Version:[/tt]" with which a mod can specify what version of FSO it was developed with. The features listed above will be removed or changed when the target version of a mod is at least the version released in this post.

[size=5pt]Previous [url=https://www.hard-light.net/forums/index.php?topic=97293.0]21.0 Release Thread[/url][/size]

Launchers, if you don't have one already:
[b]All platforms: [/b] For every day use, we recommend [url=https://www.hard-light.net/forums/index.php?topic=94068.0]Knossos[/url], an integrated solution for downloading and launching mods.

[hidden=Alternative Launchers]
Cross-platform: [url=http://www.hard-light.net/forums/index.php?topic=89162]wxLauncher 0.12.x Test Build[/url] (ongoing project for a unified launcher, you should upgrade to the latest RC/test build if you have not yet)
[b]Important:[/b] For best compatibility with FSO 3.8 and later you should use at least wxLauncher 0.12.

Windows:  [url=http://scp.fsmods.net/files/Launcher55g.zip]Launcher 5.5g[/url] ([url=http://scp.indiegames.us/builds/Launcher55g.zip]Mirror[/url]) ([url=http://www.mediafire.com/?wdvzn7hhhzh418m]Mirror[/url]) Not compatible with Windows 8+, use wxLauncher above
OS X:  Soulstorm's [url=http://www.hard-light.net/forums/index.php/topic,51391.0.html]OS X Launcher 3.0[/url]
Linux:  [url=http://www.hard-light.net/forums/index.php/topic,53206.0.html]YAL[/url] or [url=http://www.hard-light.net/wiki/index.php/Fs2_open_on_Linux/Graphics_Settings]by hand[/url] or whatever you can figure out.[/hidden]

[img]http://scp.indiegames.us/img/windows-icon.png[/img] [color=green][size=12pt]Windows (32/64-bit)[/size][/color]
[size=8pt]Compiled using GitHub Actions on Windows Server 2019 (10.0.17763), Visual Studio Enterprise 2019[/size]

[b]64-bit:[/b] ${build(groups["Win64"].mainFile)}

[b]32-bit:[/b] ${build(groups["Win32"].mainFile)}
[size=8pt]This one is based on the SSE2 Optimizations from the MSVC Compiler.[/size]

[hidden=Alternative builds]

[b]64-bit AVX:[/b] ${build(groups["Win64"].subFiles["AVX"])}
[size=8pt]This one is based on the AVX Optimizations from the MSVC Compiler (fastest build if your CPU supports AVX instructions).[/size]


[b]32-bit AVX:[/b] ${build(groups["Win32"].subFiles["AVX"])}
[size=8pt]This one is based on the AVX Optimizations from the MSVC Compiler.[/size]

[b]What are those SSE, SSE2 and AVX builds I keep seeing everywhere?[/b]
[url=http://www.hard-light.net/forums/index.php?topic=65628.0]Your answer is in this topic.[/url]
Don't want to deal with that? Use [url=https://www.hard-light.net/forums/index.php?topic=94068.0]Knossos[/url] and it will download the best build specifically for your PC!
[/hidden]

[img]http://scp.indiegames.us/img/linux-icon.png[/img] [color=green][size=12pt]Linux 64-bit[/size][/color]
[size=8pt]Compiled with Ubuntu 16.04 LTS 64-bit, GCC 5[/size]
${build(groups["Linux"].mainFile)}

These builds use a mechanism called [url=http://appimage.org/]AppImage[/url] which should allow these builds to run on most Linux distributions. However, we recommend that you compile your own builds which will result in less issues.
Alternatively, if there is a package in your software repository then you should use that. If you are the maintainer of such a package for a distribution then let us know and we will include that here.


[img]http://scp.indiegames.us/img/mac-icon.png[/img] [color=green][size=12pt]OS X[/size][/color]
[b][color=red]Not available[/color][/b] We recently lost access to our Mac CI environment which we usually used for compiling these builds so for the time being, there will be no builds for this OS.

[hidden=TrackIR Users]
[size=12pt]Important!![/size]
An external DLL is required for FSO to use TrackIR functions.  The following DLL is simply unpacked in to your main FreeSpace2 root dir.
TrackIR is only supported on Windows.
[url=http://www.mediafire.com/download.php?4zw024zrh44etse]TrackIR SCP DLL[/url] ([url=http://scp.fsmods.net/builds/scptrackir.zip]Mirror[/url]) ([url=http://scp.indiegames.us/builds/scptrackir.zip]Mirror[/url])[/hidden]

Known issues:
[list]
[li][url=https://github.com/scp-fs2open/fs2open.github.com/issues]Github issues[/url] and [url=https://github.com/scp-fs2open/fs2open.github.com/pulls]pending pull requests[/url][/li]
[li]See the list of [url=http://scp.indiegames.us/mantis/search.php?project_id=1&status_id%5B%5D=10&status_id%5B%5D=20&status_id%5B%5D=30&status_id%5B%5D=40&status_id%5B%5D=50&priority_id%5B%5D=40&priority_id%5B%5D=50&priority_id%5B%5D=60&sticky_issues=on&sortby=last_updated&dir=DESC&per_page=200&hide_status_id=-2]Fix for next release[/url] bugs - mark a bug as an elevated priority (high, urgent, immediate) to get it included in that filter.[/li]
[/list]